features:
  suppressWeather: true
  suppressTime: true
  suppressHunger: true
  suppressDamage: true
  integratedHub: true
  saveInventoryBetweenGames: true
  suppressBlockDamage: true

settings:
  startGameCountdown: 15
  gameLength: 60
  inviteLength: 30

hub:
  spawn:
    x: 83.5
    y: 235
    z: -15.5
    world: world
    fx: -89.8
    fy: 4.8

arenas:
  arenaCount: 5
  arena0:
    waitSpawn:
      x: 0.5
      y: 203
      z: -15.5
      world: world

    p1Spawn:
      x: 0.5
      y: 198
      z: -12.4
      world: world
      fx: -15.7
      fy: 22.5

    p2Spawn:
      x: 0.5
      y: 198
      z: -18.5
      world: world
      fx: 179.3
      fy: 5.1

    holeExitHeight: 197.3

  arena1:
    waitSpawn:
      x: 42.5
      y: 203
      z: -15.5
      world: world

    p1Spawn:
      x: 42.5
      y: 198
      z: -12.4
      world: world
      fx: -15.7
      fy: 22.5

    p2Spawn:
      x: 42.5
      y: 198
      z: -18.5
      world: world
      fx: 179.3
      fy: 5.1

    holeExitHeight: 197.3

  arena2:
    waitSpawn:
      x: 83.5
      y: 203
      z: -15.5
      world: world

    p1Spawn:
      x: 83.5
      y: 198
      z: -12.4
      world: world
      fx: -15.7
      fy: 22.5

    p2Spawn:
      x: 83.5
      y: 198
      z: -18.5
      world: world
      fx: 179.3
      fy: 5.1

    holeExitHeight: 197.3

  arena3:
    waitSpawn:
      x: 142.5
      y: 203
      z: -15.5
      world: world

    p1Spawn:
      x: 142.5
      y: 198
      z: -12.4
      world: world
      fx: -15.7
      fy: 22.5

    p2Spawn:
      x: 142.5
      y: 198
      z: -18.5
      world: world
      fx: 179.3
      fy: 5.1

    holeExitHeight: 197.3

  arena4:
    waitSpawn:
      x: 193.5
      y: 203
      z: -15.5
      world: world

    p1Spawn:
      x: 193.5
      y: 198
      z: -12.4
      world: world
      fx: -15.7
      fy: 22.5

    p2Spawn:
      x: 193.5
      y: 198
      z: -18.5
      world: world
      fx: 179.3
      fy: 5.1

    holeExitHeight: 197.3

scoreValues:
  WHITE_WOOL: 2
  BLACK_WOOL: 5
  CYAN_WOOL: 10
  RED_WOOL: 20
  YELLOW_WOOL: 40