name: DropShotMinigame
version: 1.0
author: MysterySpace
main: net.mysteryspace.dropshotminigame.Main
api-version: 1.13

commands:
  dropshot:
    description: Actions related to DropShot games - creategame, invite, leave