name: DropShotMinigame
version: 1.0
author: MysterySpace
main: net.mysteryspace.dropshotminigame.Main
api-version: 1.13

commands:
  createGame:
    description: Create a new match

  invite:
    description: Invite a player to your match

  acceptInvite:
    description: Accept an invite